# Efficient Data Handling for Renewable Energy Consumption Using NumPy

#### Objectives:

1.NumPy Arrays: We will create a NumPy array to efficiently store and manipulate numerical data for energy consumption (in MWh) from different renewable energy sources.

2.Basic Operations: We will perform basic operations such as calculating the sum, mean, standard deviation, and reshaping the data for further analysis.

### Step 1. Import NumPy and Create a Dataset

We’ll begin by importing the NumPy library and creating a NumPy array to represent energy consumption data for different renewable energy sources.

In [2]:
import numpy as np

In [3]:
# Energy consumption in MWh for different renewable sources: Solar, Wind, Hydropower, Geothermal, Biomass
ec = [1200, 3400, 2900, 1800, 2500]
energy_consumption = np.array(ec)

# Print the array
print("Energy Consumption (in MWh) for Different Renewable Sources:")
print(energy_consumption)

Energy Consumption (in MWh) for Different Renewable Sources:
[1200 3400 2900 1800 2500]


In [4]:
type(ec)

list

In [5]:
type(energy_consumption)

numpy.ndarray

We’ve created a NumPy array energy_consumption that stores energy consumption in megawatt-hours (MWh) for different renewable sources: Solar, Wind, Hydropower, Geothermal, and Biomass.

The array provides efficient storage and manipulation of numerical data, which makes it suitable for large datasets.

In [6]:
A = np.ones(4)
A2 = np.ones((2,2))
print(A)
print("\n", A2)

[1. 1. 1. 1.]

 [[1. 1.]
 [1. 1.]]


In [7]:
M = np.zeros(4)
print(M)

[0. 0. 0. 0.]


In [8]:
M = np.identity(4)
print(M)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Step 2: Perform Basic Operations


#### 2.1. Calculate the Sum of Energy Consumption

We’ll calculate the total energy consumption across all renewable sources.

In [9]:
# Calculate the total energy consumption
total_consumption = np.sum(energy_consumption)

print(f"Total Energy Consumption: {total_consumption} MWh")

Total Energy Consumption: 11800 MWh


The np.sum() function efficiently sums all the values in the array to calculate the total energy consumption across all sources.

#### 2.2. Calculate the Mean (Average) Energy Consumption

In [10]:
# Calculate the mean energy consumption
mean_consumption = np.mean(energy_consumption)

print(f"Mean Energy Consumption: {mean_consumption:.2f} MWh")


Mean Energy Consumption: 2360.00 MWh


The np.mean() function calculates the average energy consumption by dividing the total consumption by the number of sources.

#### 2.3. Calculate the Standard Deviation of Energy Consumption

In [11]:
# Calculate the standard deviation of energy consumption
std_deviation = np.std(energy_consumption)

print(f"Standard Deviation of Energy Consumption: {std_deviation:.2f} MWh")

Standard Deviation of Energy Consumption: 781.28 MWh


The np.std() function calculates how much the energy consumption values deviate from the mean, providing insights into the variability of the data.


#### 2.4. Reshaping the Array

Now, let’s reshape the array to demonstrate how we can manipulate its structure. We’ll reshape it into a 5x1 array.

In [12]:
# Reshape the array (to 5 rows and 1 column)
energy_consumption2 = np.array([1200, 3400, 2900, 1800, 2500,1800])
reshaped_array = energy_consumption2.reshape((3,2))

print("Reshaped Energy Consumption Array (3x2):")
print(reshaped_array)

Reshaped Energy Consumption Array (3x2):
[[1200 3400]
 [2900 1800]
 [2500 1800]]


In [13]:
# flatten
reshaped_array.flatten()

array([1200, 3400, 2900, 1800, 2500, 1800])

In [14]:
#transpose
reshaped_array.T

array([[1200, 2900, 2500],
       [3400, 1800, 1800]])

#### 2.5. Resizing the Array
Adds/duplicates the elements to existing array to satisfy given input dimentions

In [15]:
resize_array = np.resize(reshaped_array, (3,3))
resize_array

array([[1200, 3400, 2900],
       [1800, 2500, 1800],
       [1200, 3400, 2900]])

The reshape() function changes the shape of the array from a 1D array (of length 5) to a 2D array with 5 rows and 1 column, allowing for further analysis or integration into matrix operations.

In [16]:
# np.array(): Creates a NumPy array from a list or other iterable.
# np.random.randint(0, 10, 1): Generates a random integer between 0 and 10, with size 1.
# np.unique(): Finds the unique elements in an array and returns them in sorted order.
# np.dot(): Computes the dot product of two arrays or matrices.
# np.power(a, 2): Raises each element of array a to the power of 2.
# np.sqrt(a): Returns the square root of each element in the array a.
# np.ones(): Creates a new array of the specified shape, filled with ones.
# np.zeros(): Creates a new array of the specified shape, filled with zeros.
# np.max(): Returns the maximum value in the array.
# np.arange(10): Creates an array with evenly spaced values from 0 to 9. 

In [17]:
np.array(reshaped_array)

array([[1200, 3400],
       [2900, 1800],
       [2500, 1800]])

In [18]:
np.random.randint(0,10,5)

array([1, 4, 1, 1, 3], dtype=int32)

In [19]:
np.unique(reshaped_array)

array([1200, 1800, 2500, 2900, 3400])

In [20]:
resize_array = np.resize(resize_array,(3,2))


In [26]:
arr  = resize_array
arr

array([[1200, 3400],
       [2900, 1800],
       [2500, 1800]])

In [27]:
arr2 = reshaped_array
arr2

array([[1200, 3400],
       [2900, 1800],
       [2500, 1800]])

In [29]:
np.dot(arr , arr2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [24]:
np.power(reshaped_array, 2)

array([[ 1440000, 11560000],
       [ 8410000,  3240000],
       [ 6250000,  3240000]])

In [25]:
np.sqrt(reshaped_array)

array([[34.64101615, 58.30951895],
       [53.85164807, 42.42640687],
       [50.        , 42.42640687]])

### Conclusion

In this lab assignment, we used NumPy to create an array representing energy consumption from various renewable sources. By leveraging NumPy’s powerful functions, we efficiently performed basic operations such as summing the data, calculating the mean and standard deviation, and reshaping the array for more complex data manipulations. NumPy's efficient handling of numerical data makes it an essential tool for energy-related data analysis and large-scale computations.